### PR TITLE
Collection of smaller bug fixes and enhancements

### PR DESCRIPTION
**Pull request by jhauffa**
Dear Jean-Marc,
I have used jahmm in a university project with great success, and fixed some bugs and made some enhancements to the code along the way. I have cleaned up my modifications and would like to contribute them to your repository. This branch collects a bunch of smaller patches, mostly concerned with making the build process and the unit tests run cleanly. In a second branch (https://github.com/jhauffa/jahmm/tree/logspace), I have prepared a more substantial enhancement, an implementation of Baum-Welch in log-space. I will send a pull request for that branch once you have decided how to proceed with this one.

With best regards,
Jan

### CODE REVIEW

**Comment by jhauffa** [comment]
Since there has been no response to my pull request, I will maintain the changes in my own fork for now. I am still very much open to collaboration!

**Comment by LeGaumaisMasque** [comment]
Thank you much Jan, and apologies for missing your pull request.

I don't work on this library anymore, I wrote it in another life. Tell me if you'd be interested in being the owner of this repository, I'd transfer it to you.

Regards,
JM

**Comment by jhauffa** [comment]
I understand completely, and would be happy to take over maintenance of jahmm with your permission. I don't think it is necessary to transfer the repository, I can just keep working on my fork. My plan would be to update the repo URL in the documentation, make a release, and upload the JARs to a Maven repository or such to get the word out. Would that be okay with you?

**Comment by LeGaumaisMasque** [comment]
I agree with you working on you working on your fork. Thank you for your work!

**Pull request closed without merging**
